# syntax=docker/dockerfile:1.6
FROM golang:1.22-bookworm AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
RUN go build -trimpath -ldflags="-s -w" -o /out/party-state ./cmd/party-state

FROM gcr.io/distroless/base-debian12:nonroot
USER nonroot:nonroot
EXPOSE 3130
COPY --from=build /out/party-state /party-state
ENTRYPOINT ["/party-state"]
