version = 5.2.2
archive_dir = /etc/letsencrypt/archive/earflow.ru
cert = /etc/letsencrypt/live/earflow.ru/cert.pem
privkey = /etc/letsencrypt/live/earflow.ru/privkey.pem
chain = /etc/letsencrypt/live/earflow.ru/chain.pem
fullchain = /etc/letsencrypt/live/earflow.ru/fullchain.pem
[renewalparams]
account = 9fd0c45e87f93d418e908f3c503a31a1
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
