#!/bin/bash
# =============================================================================
# Secrets Setup Script
# Music Platform - Secure Secrets Generation
# =============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SECRETS_DIR="${PROJECT_DIR}/secrets"

# Secret files
declare -A SECRETS=(
    ["postgres_password"]="32"
    ["jwt_secret"]="64"
    ["service_secret"]="64"
    ["minio_root_password"]="32"
    ["backup_encryption_key"]="32"
)

# Generate secure random string
generate_secret() {
    local length="$1"
    openssl rand -base64 "$length" | tr -d '\n' | head -c "$length"
}

# Setup secrets directory
setup_directory() {
    log_info "Setting up secrets directory..."
    
    mkdir -p "$SECRETS_DIR"
    chmod 700 "$SECRETS_DIR"
    
    # Add to .gitignore if not already present
    local gitignore="${PROJECT_DIR}/.gitignore"
    if ! grep -q "^secrets/$" "$gitignore" 2>/dev/null; then
        echo "secrets/" >> "$gitignore"
        log_info "Added secrets/ to .gitignore"
    fi
}

# Generate all secrets
generate_secrets() {
    log_info "Generating secrets..."
    
    for secret_name in "${!SECRETS[@]}"; do
        local secret_file="${SECRETS_DIR}/${secret_name}.txt"
        local secret_length="${SECRETS[$secret_name]}"
        
        if [[ -f "$secret_file" ]]; then
            log_warn "Secret '$secret_name' already exists, skipping"
            continue
        fi
        
        local secret_value=$(generate_secret "$secret_length")
        echo -n "$secret_value" > "$secret_file"
        chmod 600 "$secret_file"
        
        log_success "Generated: ${secret_name} (${secret_length} chars)"
    done
}

# Generate .env file from secrets
generate_env_file() {
    local env_file="${PROJECT_DIR}/.env.production"
    
    log_info "Generating .env.production file..."
    
    cat > "$env_file" << 'EOF'
# =============================================================================
# Production Environment Configuration
# Music Platform
# Generated by setup-secrets.sh
# =============================================================================

# Node environment
NODE_ENV=production

# Domain configuration (UPDATE THESE!)
DOMAIN=your-domain.com
EMAIL=admin@your-domain.com

# PostgreSQL
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=music_platform
POSTGRES_USER=music_user
EOF
    
    # Add secrets references
    echo "POSTGRES_PASSWORD=$(cat "${SECRETS_DIR}/postgres_password.txt")" >> "$env_file"
    echo "" >> "$env_file"
    
    cat >> "$env_file" << 'EOF'
# Redis
REDIS_HOST=redis
REDIS_PORT=6379

# MinIO
MINIO_ENDPOINT=http://minio:9000
MINIO_ROOT_USER=minioadmin
EOF
    
    echo "MINIO_ROOT_PASSWORD=$(cat "${SECRETS_DIR}/minio_root_password.txt")" >> "$env_file"
    echo "" >> "$env_file"
    
    cat >> "$env_file" << 'EOF'
# Storage
STORAGE_MODE=minio
MINIO_BUCKET_AUDIO=music-audio
MINIO_BUCKET_COVERS=music-covers

# JWT
EOF
    
    echo "JWT_SECRET=$(cat "${SECRETS_DIR}/jwt_secret.txt")" >> "$env_file"
    echo "JWT_EXPIRES_IN=7d" >> "$env_file"
    echo "" >> "$env_file"
    
    cat >> "$env_file" << 'EOF'
# Service communication
EOF
    
    echo "SERVICE_SECRET=$(cat "${SECRETS_DIR}/service_secret.txt")" >> "$env_file"
    echo "ALLOWED_SERVICES=api-gateway,auth-service,upload-service,database-service,recommendations-service,track-processor,playlist-service,lyrics-service,party-state-service" >> "$env_file"
    echo "" >> "$env_file"
    
    cat >> "$env_file" << 'EOF'
# Service URLs
AUTH_SERVICE_URL=http://auth-service:3001
UPLOAD_SERVICE_URL=http://upload-service:3002
DATABASE_SERVICE_URL=http://database-service:3003
RECOMMENDATIONS_SERVICE_URL=http://recommendations-service:3006
PLAYLIST_SERVICE_URL=http://playlist-service:3020
LYRICS_SERVICE_URL=http://lyrics-service:3010
PARTY_SERVICE_URL=http://party-state-service:3130

# Frontend
REACT_APP_API_URL=/api
REACT_APP_WS_URL=/socket.io

# Recommendations
RECO_SESSION_TTL_SECONDS=3600
RECO_BATCH_SIZE=20
RECO_MIN_COLD_START=5
RECO_DIVERSITY_FACTOR=0.3

# Rate Limiting
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX_REQUESTS=100

# Logging
LOG_LEVEL=info
LOG_FORMAT=json

# Backup
ENCRYPT_BACKUPS=true
RETENTION_DAYS=30
EOF
    
    chmod 600 "$env_file"
    log_success "Generated: .env.production"
}

# Validate secrets
validate_secrets() {
    log_info "Validating secrets..."
    local errors=0
    
    for secret_name in "${!SECRETS[@]}"; do
        local secret_file="${SECRETS_DIR}/${secret_name}.txt"
        local expected_length="${SECRETS[$secret_name]}"
        
        if [[ ! -f "$secret_file" ]]; then
            log_error "Missing: ${secret_name}"
            ((errors++))
            continue
        fi
        
        local actual_length=$(wc -c < "$secret_file" | tr -d ' ')
        if [[ "$actual_length" -lt "$expected_length" ]]; then
            log_warn "Secret '${secret_name}' is shorter than expected (${actual_length} < ${expected_length})"
        fi
        
        # Check file permissions
        local perms=$(stat -c "%a" "$secret_file" 2>/dev/null || stat -f "%OLp" "$secret_file" 2>/dev/null)
        if [[ "$perms" != "600" ]]; then
            log_warn "Secret '${secret_name}' has incorrect permissions: ${perms} (should be 600)"
            chmod 600 "$secret_file"
        fi
    done
    
    if [[ $errors -gt 0 ]]; then
        log_error "Validation failed with ${errors} errors"
        return 1
    fi
    
    log_success "All secrets validated"
    return 0
}

# Rotate a specific secret
rotate_secret() {
    local secret_name="$1"
    
    if [[ -z "${SECRETS[$secret_name]:-}" ]]; then
        log_error "Unknown secret: ${secret_name}"
        exit 1
    fi
    
    local secret_file="${SECRETS_DIR}/${secret_name}.txt"
    local backup_file="${secret_file}.backup.$(date +%Y%m%d%H%M%S)"
    
    # Backup existing secret
    if [[ -f "$secret_file" ]]; then
        cp "$secret_file" "$backup_file"
        chmod 600 "$backup_file"
        log_info "Backed up existing secret to: $(basename "$backup_file")"
    fi
    
    # Generate new secret
    local secret_length="${SECRETS[$secret_name]}"
    local secret_value=$(generate_secret "$secret_length")
    echo -n "$secret_value" > "$secret_file"
    chmod 600 "$secret_file"
    
    log_success "Rotated: ${secret_name}"
    log_warn "Remember to restart services that use this secret!"
}

# Show usage
usage() {
    echo "Secrets Management Tool"
    echo ""
    echo "Usage: $0 <command> [args]"
    echo ""
    echo "Commands:"
    echo "  setup      - Generate all secrets and .env.production"
    echo "  validate   - Validate existing secrets"
    echo "  rotate     - Rotate a specific secret"
    echo "  list       - List all secrets (names only)"
    echo ""
    echo "Examples:"
    echo "  $0 setup"
    echo "  $0 rotate jwt_secret"
    echo "  $0 validate"
}

# Main execution
main() {
    local command="${1:-}"
    
    case "$command" in
        setup)
            setup_directory
            generate_secrets
            generate_env_file
            validate_secrets
            echo ""
            log_success "Secrets setup complete!"
            log_warn "IMPORTANT: Keep the secrets/ directory secure and backed up!"
            log_info "Use .env.production for production deployment"
            ;;
        validate)
            setup_directory
            validate_secrets
            ;;
        rotate)
            if [[ -z "${2:-}" ]]; then
                log_error "Usage: $0 rotate <secret_name>"
                echo "Available secrets: ${!SECRETS[*]}"
                exit 1
            fi
            rotate_secret "$2"
            ;;
        list)
            echo "Available secrets:"
            for secret_name in "${!SECRETS[@]}"; do
                local secret_file="${SECRETS_DIR}/${secret_name}.txt"
                local status="✗"
                [[ -f "$secret_file" ]] && status="✓"
                echo "  ${status} ${secret_name}"
            done
            ;;
        *)
            usage
            exit 1
            ;;
    esac
}

main "$@"
