package cryptoutil

import (
	"encoding/hex"
	"testing"
)

// Reference vectors generated by Node crypto.pbkdf2Sync with the same params
// as auth-service.
const (
	nodeSalt600k = "aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899"
	nodeHash600k = "1ed68e415563dafe53d0bc74f4bdcbb1ed970bc6474377b34a220c29d9174a60632045614ae43bd0c82cbd0fd4463b3d91af2c3b221767f5e030f3eba7a51610"
	nodeHash100k = "06d2f66e8cf3de0ae020bbe8f61202288609662c4128c251e67c92553a107cc2f65f1f4939734e36997512aa2c8dee32b24b2634b2b991c28e088046a8e1f0e9"
)

func TestHashPasswordNodeCompat(t *testing.T) {
	got := HashPassword("MySecretPass1", nodeSalt600k, 600000, 64)
	if got != nodeHash600k {
		t.Fatalf("600k mismatch\n got %s\nwant %s", got, nodeHash600k)
	}
	gotLegacy := HashPassword("MySecretPass1", nodeSalt600k, 100000, 64)
	if gotLegacy != nodeHash100k {
		t.Fatalf("legacy mismatch\n got %s\nwant %s", gotLegacy, nodeHash100k)
	}
}

func TestConstantTimeHexEquals(t *testing.T) {
	if !ConstantTimeHexEquals(nodeHash600k, nodeHash600k) {
		t.Fatal("equal values should match")
	}
	if ConstantTimeHexEquals(nodeHash600k, nodeHash100k) {
		t.Fatal("different values should not match")
	}
	if ConstantTimeHexEquals("abc", "abcd") {
		t.Fatal("different lengths should not match")
	}
}

// Node-generated encryptData v2 payload for {firstName:"Alex",lastName:"Petrov"}
// with ENCRYPTION_KEY 0011...ddff and the salt below.
func TestDecryptNodePayload(t *testing.T) {
	encKey, _ := hex.DecodeString("00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff")
	salt := "f0e1d2c3b4a5968778695a4b3c2d1e0ff0e1d2c3b4a5968778695a4b3c2d1e0f"
	payload := EncryptedPayload{
		V:         2,
		Encrypted: "fde51b8d2e818817a409ec6f44bba91fa3d861d46645143c21eb538a83e5155849b1543d79df3e42",
		IV:        "1e5d181321bbd15c95cc9aba603ecb8f",
		AuthTag:   "b4fb2563ae4240765fd41c8e2e314f0b",
	}
	plain, err := DecryptPayload(encKey, salt, payload, 600000, 100000, 32)
	if err != nil {
		t.Fatalf("decrypt: %v", err)
	}
	got := string(plain)
	want := `{"firstName":"Alex","lastName":"Petrov"}`
	if got != want {
		t.Fatalf("decrypt mismatch\n got %s\nwant %s", got, want)
	}
}

func TestEncryptRoundTrip(t *testing.T) {
	encKey, _ := hex.DecodeString("00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff")
	salt := "f0e1d2c3b4a5968778695a4b3c2d1e0ff0e1d2c3b4a5968778695a4b3c2d1e0f"
	plain := []byte(`{"firstName":"Ivan","lastName":"Sidorov"}`)
	payload, err := EncryptPayload(encKey, salt, plain, 600000, 32)
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}
	if payload.V != 2 {
		t.Fatalf("expected v=2, got %d", payload.V)
	}
	out, err := DecryptPayload(encKey, salt, *payload, 600000, 100000, 32)
	if err != nil {
		t.Fatalf("decrypt: %v", err)
	}
	if string(out) != string(plain) {
		t.Fatalf("roundtrip mismatch: %s", out)
	}
}
